### ISSUE TITLE
Async Loading + Usage of Propel

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/Propel#12]
*Please close this bug if we don't expect developers to load the propel library as a separate async script.*

In most third party libraries I've seen the script URL take an extra parameter for a method to call on the window OR it just has a specific callback on the window object that it'll look for and call if it exists, not sure if there is a better option than this.

Would it be worth adding something along these lines to Propel?

**Comment by addyosmani** [comment]
Hmm. I'd be interested in understanding if there's a compelling reason for Propel to not support being asynchronously loaded. /sub anyway :)

**Comment by gauntface** [comment]
its not that it won't but the developer we need some way to detect when window.goog.propel.Client is defined if it's from an external script.

Unless I'm over thinking things?

**Comment by wibblymat** [comment]
I can totally see where you're coming from, but will people really use it? You can already get it to work async by just loading Propel in first:

```
<script async src="propel/client.js"></script>
<script async src="app.js"></script>
```

The `async` attribute still guarantees order of execution, IIUIC.

**Comment by gauntface** [comment]
I thought it was defer that would execute in order not async.

**Comment by gauntface** [comment]
Background of my thinking was that given progressive web apps are the name
of the game at the moment, async should be something we support.

But like I said calling a callback or firing an event is the only way I've
seen this be "supported".

**Comment by gauntface** [comment]
Going to close this and see if anyone requests this.
