### ISSUE TITLE
Add requestPermission to the client

### ISSUE THREAD

**Issue by owencm** [GoogleChrome/Propel#17]
I like conceptually breaking subscribing away from requesting permission, because:

a) The best way of requesting permission (i.e. via the Notifications API) doesn't require a network round trip whereas calling subscribe would
b) Conceptually I think it's clear to think of these as separate actions, one that just must follow the other. It seems surprising initially that to request permission you need to subscribe the device

**Comment by wibblymat** [comment]
We can certainly add `requestPermission`. It's optional, of course, because if you don't handle permissions yourself then subscribe will still do it.
