### ISSUE TITLE
Service Worker Registration

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/Propel#30]
cc @jeffposnick @wibblymat @paullewis @petele

Me and Pete were discussion how to use the Propel library and one of the things that came up was how to use it with your own SW.

This isn't obvious and passing in a worker url and scope for something you've registered already for different reasons feels a bit weird to give the url and scope for.

The API at present is:

    new Client({workerUrl: '/sw.js', scope: './'});

Would anyone object to changing this to something a bit more permanent of:

    new Client('/sw.js'); // Scope is predefined as current script path + /.goog.propel.push

    new Client('./sw.js', './');

    new Client(swRegistration); 

Service work url can be obtained from the installing, waiting or active service worker object and the scope can be retrieved from the registration object.

Is there any downsides / edge cases to this?

The only reason I'm proposing ditching the options object is the worker.js file is currently empty and I'm not convinced shipping a default service worker is a good idea here, shipping with a library to help generate notifications makes sense, but it will still require some work on the developers behalf and expecting worker.js to exist in the same place as the client.js file feels a bit risky / unpredictable. The above at least forces some decision to be made.

What do people think? This is new and is likely to come up again with any libraries around background sync.

**Comment by jeffposnick** [comment]
I'm not fully up on the `Propel` API surface, so apologies if this doesn't make sense. I had a quick chat with @petele and it seemed like the following would be a reasonable interface for each of those two use cases:

```js
// When you want to use your existing service worker and add in Propel:
navigator.serviceWorker.register('/your-own-sw.js').then(registration => {
  new Client(registration);
});
```

```js
// When you want Propel to provide the service worker for you:
new Client('/propels-sw.js');
```

I guess that maps to the third choice in your list?

**Comment by gauntface** [comment]
Thanks Jeff, this is essentially the options I proposed above. 

@addyosmani @jakearchibald for thoughts.

**Comment by jakearchibald** [comment]
Seems ok, but would need to see some example code for the expected usage of the lib to give better feedback.

**Comment by gauntface** [comment]
You can checkout the readme on this branch for a rough idea of how this can be used: https://github.com/GoogleChrome/Propel/tree/doc-sweep

**Comment by gauntface** [comment]
Chatting with @wibblymat and @jakearchibald, sounds like requiring a service worker url sounds like the best approach and removing the worker.js file altogether and moving to a notification library makes most sense.

**Comment by petele** [comment]
@jakearchibald - here's roughly how I'd want to use it...

```
var PropelClient;
var propel;

if ('serviceWorker' in navigator) {
  PropelClient = window.goog.propel.Client;
  navigator.serviceWorker
           .register('/service-worker.js')
           .then(function(reg) {
              console.log('Service Worker Registered', reg); 
              if (PropelClient.supported()) {
                propel = new PropelClient(reg);
                propel.addEventListener('statuschange', function(evt) {
                  // DO MAGIC HERE
                  console.log('[PROPEL] event', evt.permissionStatus, evt);
                });
              }
            }
          );
}
```

**Comment by gauntface** [comment]
I'm just adding tests to propel, so once it's in I'll fix it up to take a
registration and remove the current worker URL which everyone seems happy
with.

Thanks for the input everyone.

**Comment by paullewis** [comment]
@petele @gauntface I think that's exactly the code I'd want as well. Looks very not magical to get the registration and pass it to PropelClient, which gets a thumbs up from me.
