### ISSUE TITLE
no quick start - must run gulp to build useful file

### ISSUE THREAD

**Issue by petele** [GoogleChrome/Propel#31]
I had to download the whole repo, then run gulp to build client.js, i should be able to just grab a quick client js file and go.

**Comment by gauntface** [comment]
We do now have an npm and bower release, the script to publish is still in flight but will hopefully land. When it does I'll update the ReadMe to make use of the npm module.

**Comment by addyosmani** [comment]
:+1: Post the release script landing, an `npm install` making this useful should be sufficient here.

**Comment by gauntface** [comment]
Readme is updated so this can be closed now.
