### ISSUE TITLE
Increase Visibility Time Of Web Push Notification

### ISSUE THREAD

**Issue by sid5491** [GoogleChrome/Propel#34]
Hi

As of now the default time of visibility for my push message on chrome browser is 19 seconds which is too low, But Other push services like OneSignal, Pushcrew, Let Reach are having visibility time of upto 3 minutes for there messages. How can i do that, Need some help with this please

Thank You

**Comment by wibblymat** [comment]
Hi there,

On Android, notifications will stay around until dismissed. However, on desktop the default is for the notification to disappear after a short time.

If you want the notification to hang around you can set the `requireInteraction` parameter to `true` when creating the notification. Now it will stay on screen until it is clicked.

For an example, see https://googlechrome.github.io/samples/notifications/requireInteraction.html

**Comment by sid5491** [comment]
Thank You Soo Much :)
