### ISSUE TITLE
Wrong endpoint returned...

### ISSUE THREAD

**Issue by dvas0004** [GoogleChrome/Propel#82]
I think this may be more of a chrome issue since the underlying service worker (PushManager) is returning the wrong endpoint, but just in case:

- When running:
```
var pushClient = new PushClient('/sw.js');
      pushClient.addEventListener('statuschange', function(event) {
	console.log('pushClient:');
	console.log(JSON.stringify(event.currentSubscription));
   }
```
we get something like:

`{"endpoint":"https://android.googleapis.com/gcm/send/[...]","keys":{"p256dh":"BIdjZil_ehfT_MQt95qRFB3qn-55ccb1qYrc-5g0lvWK3XYvF2drD08ulRO_2ljjZVb7vA9R3OydI7QMnHR6C24=","auth":"75pCFtk04rNYL8ozHMEhfQ=="}}`

but now if we try to send encrypted data using the new PushAPI specs (i'm using [pywebpush](https://github.com/mozilla-services/pywebpush)) I have to use a different API endpoint: 

`{"endpoint":"https://gcm-http.googleapis.com/gcm/[...]`

[The chrome specific webpush library does a quick switcheroo of the URLs but that's cheating ;)](https://github.com/GoogleChrome/web-push-encryption/blob/19a91f5c29ddd8dde7bd186fa67c9bf1548a2def/src/push.js#L69)

It would probably be useful to mention this in the docs

**Comment by gauntface** [comment]
It's possible to send encrypted messages with this endpoint but it requires a different format:

See: https://github.com/gauntface/simple-push-demo/blob/a00963aad6b08cb6539f9899258ba2380967ffaa/src/scripts/app-controller.js#L277

I'd argue what we are doing there is wrong, but it was a temporary measure. Eitherway, it should be handled by server side libraries in the meantime and all this will be changing soon when Chrome supports web push protocol.
