### ISSUE TITLE
Ping endpoint on unsubscribe?

### ISSUE THREAD

**Issue by wibblymat** [GoogleChrome/Propel#9]
Is there actually any point in pinging the endpoint when the user unsubscribes? Certainly for GCM it doesn't make any difference in practice, because GCM will let the server know if the subscription isn't valid any more and the server needs to be able to handle that anyway.

CC: @gauntface @owencm

**Comment by ithinkihaveacat** [comment]
GCM will only let the server know after failing to deliver the *next* message though, right? If you're trying to correlate unsubscribes with some message or activity, you might want to find out ASAP. (For example, to avoid sending a particular message to all subscribers if the first few people to receive it immediately unsubscribed.)

**Comment by gauntface** [comment]
I think it's good practice and for analytics is helpful.

**Comment by gauntface** [comment]
We've removed the endpoint auto-pinging and moved it to a seperate helper, so I think for now this can be closed.
